### ISSUE TITLE
Draggable tokens to represent players and monsters

### ISSUE THREAD

**Issue by apclary** [apclary/dungeon-revealer#35]
Add player/monster tokens. The impetus is that while players can visualize the map, they have to mentally track their own position.  Beyond that, it may be necessary to stake a claim to a position for the sake of game rules. 

Operations to be performed on tokens:
- Create
- Move
- Delete

Other suggestions:

- Color selection for tokens, so monsters of a certain type could all be a certain color. Perhaps from a palette.
- Adjustable sizes for tokens, or ability to pick from a palette of size options at creation time. Since we do not know the scale of user's maps in advance, they might want tokens to correspond to their own grid system.
- Ability to add a letter or sub image to a token to more easily identify that token, perhaps "A" for a character named "Alex" or the image of a bow for a player with a bow.
- Players could move tokens. A complex permissions system may be overkill, but it might be nice for players to move tokens rather than constantly coordinating with the DM, e.g. "move my token 5 down and 2 to the left".

**Comment by n1ru4l** [comment]
I also thought about a "Point Of Interest" Feature which allows Players or the DM to mark an area on the map (with a simple touch or click) so the other players/ the dm can see what point of a map they are referring to.

**Comment by Azkel** [comment]
Hi guys, I was thinking about adding some kind of tokens feature to the app, as it would come in handy for us. 

I was wondering how I could tackle this, and here are two ideas:
- Tokens could just be a generic circle with text **P1**, **P2**, ..., **Pn** for Player 1, Player 2 etc. and **M1**, **M2**, ..., **Mn** for monsters. Other option would be a label system for each of them
- Instead of making them draggable, perhaps if each token was unique (option 1 from point above) or had unique label (option 2 from point above), just trying to draw that token on the other place of the map would remove it from the old one?

And token sizes could be adjusted the same way as brush is right now. 

Any opinions?

**Comment by apclary** [comment]
A simple approach would be to have a pool of perhaps eight colored circles representing the possible token types. Dragging a circle onto the board would result in the token being assigned a number (e.g. the first purple token would be assigned "1", the second would be "2", etc.).

@n1ru4l mentioned he was working on a CV approach to recognizing grid lines, that would allow snap-to-grid functionality.

My feeling is that there are many ways to add features to the basic principle, but just having something very simple and easy-to-code achieves 80% of the user value.

**Comment by Azkel** [comment]
Yea, I am discussing with my friend between implementing this or #23 , as either one would fit our  needs as for this app (perhaps we will do both, if it will go smoothly). But approach with eight circles should be easy as well, so probably will stick to that. At the beginning just with a brush size, will wait for the grid lines recognition to adjust the code... Or leave it for someone else ;)

**Comment by n1ru4l** [comment]
hey @Akzel, welcome on board it is always nice to have new contributors 🎉

I am currently on hold with my grid detection (as I run into some limitations and performance issues). I need to investigate a bit more. Before adding this advanced feature I will try to add a simple add grid feature which allows adding a grid by interactively setting the xStart, yStart, cellSize and gutterWidth (with a visual preview). I cannot give an ETA yet, but I will try to work on this on the weekend.

We can definitely add draggable tokens without first implementing the grid.

My main concerns for not having a grid before implementing this are the following:

We do not know the size a token must have (so that must be configurable). Of course, even with a grid, you need some setting to comply with the different obstacle/creature tokens

I would recommend implementing the draggable tokens as SVG elements on the object layer

https://github.com/apclary/dungeon-revealer/blob/a2d41c0ae03253a159d2eb9a381bad9709b351f0/src/object-layer.js#L95-L119

Instead of having a hardcoded amount of 8 tokens I would prefer right clicks which opens a menu for adding new tokens. With a right-click on a token on the board, you will also get an option for removing a token.

Let me know what you think.

**Comment by Azkel** [comment]
@Quintasan

**Comment by Azkel** [comment]
As for draggable tokens - sounds reasonable. As for the right-click adding to the board, I see a little bit of problem with adjusting token size to fit the grid, as this option should be then configured somewhere else. Option with just putting it next to the brush in my opinion is more intuitive (after all, left-side menu is a toolbox, so all tools should probably be in it), and allow us to implement possibility to change size by imitating the UI of brush.

**Comment by n1ru4l** [comment]
Sounds reasonable!

**Comment by n1ru4l** [comment]
Sounds good to me!

**Comment by Azkel** [comment]
As I had some time today, I did first draft of the code - you can see result on [this video.](https://smyk.it/files/DungeonRevealer.mp4)

Right now each token has a separate colour, and I had set amount of tokens to 28. Of course if you will have more than few tokens, you will quickly get lost which number is relevant to which colour, so some additional number will have to be added to the circle.  

Would greatly appreciate any opinions about the UI, as the look of the tokens (and their relation to the brush circle radius) will certainly be changed in the upcoming days.

**Comment by apclary** [comment]
Great job! 

I imagine the practical use case is that in a party of 3-5 players, each would want to be represented by their own color, and each monster type in a fight would also get its own color, with individual monsters of the same type differentiated by numbers. As the battle progresses, monsters would be removed from the board.

Here are a few possibilities:

- Clicking on a token open the token menu and set the <select> value to that token. 
- To facilitate even easier removal of monster tokens, a trash can could appear on the screen somewhere while a token is in a drag state. Dragging the token to the trash can would immediately delete it.
- You might also add a button on the token menu to remove all tokens. 
- A "clone" button on the token menu that duplicates the size and color of the selected token

**Comment by n1ru4l** [comment]
Looks good! how about filling the whole token instead of just having a border?

**Comment by n1ru4l** [comment]
There is a cool library for color pickers available: https://casesandberg.github.io/react-color/

**Comment by Azkel** [comment]
I was doing a little analysis about which lib to use for right-click menu, and at the end I ended up with selecting [react-context-menu](https://www.npmjs.com/package/react-context-menu). I also taken into consideration two others libraries:
- [react-contexify](https://www.npmjs.com/package/react-contexify) - too much (dev) dependencies in my opinion, I like to keep things as independent as possible :D
- [react-contextmenu](https://www.npmjs.com/package/react-contextmenu) - info that they are looking for maintainers is always a bad omen when it comes to support/fixes in the future, so I also prefer not to use this one

As you guys are the ones owning the repo, I would like to confirm that you are fine with my choice before I'll start implementation. Care for any opinion on this matter?

I'll probably try to include that react-color in the menu as well ;)

**Comment by apclary** [comment]
I’ll trust you or @n1ru4l on the technical or usability merits of either, but I do notice the selected library has far fewer weekly downloads than the others (120 vs. 24,000). I generally prefer to use the most popular library available that gets the job done for future proofing/googling but again, I trust either of you so if one has better features or is simpler to use then feel free, just wanted to double check.

**Comment by Azkel** [comment]
> I’ll trust you or @n1ru4l on the technical or usability merits of either, but I do notice the selected library has far fewer weekly downloads than the others (120 vs. 24,000). I generally prefer to use the most popular library available that gets the job done for future proofing/googling but again, I trust either of you so if one has better features or is simpler to use then feel free, just wanted to double check.
That's also a valid point I guess. I'll come back to this topic later on, when I'll figure out how to map clicking on PanZoom (as it catches all mouse events) to proper svg entry on ObjectLayer ;) 

> Also this project could use more contributors, so once you submit a PR or two I’ll add you if you want.
Not sure how much I'll be able to provide later on - normally I just add functionalities that I need for my own purposes and stop working on the projects... But we will see ;)

**Comment by Azkel** [comment]
I had some issues with adding the right-menu context, so for the moment I gave up and provided posibility to remove token on right-click. Additionally color picker has been implemented - [video](https://smyk.it/files/DR.mp4).

Any opinions? If that would be enough (and based on the primary post I would say it is) I can submit a pull request for it.
