### ISSUE TITLE
Improve Send Performance

### ISSUE THREAD

**Issue by n1ru4l** [apclary/dungeon-revealer#54]
I noticed that the more of a map is revealed the longer the sending/receiving aka time to send until the player sees the updates increases drastically.  This might be because sending a black image is faster than sending the actual map.

Maybe it would be possible to send the actual map initially and only send the updated fog image after updates. This would allow users to see the whole map (not just the revealed parts) if they use the developer tools to inspect the DOM or trace the HTTP requests. However, since this tool is intended for home use I do not think cheating would be an issue.

Do you have any other optimizations in mind? Detecting affected areas (that the dm draws on) and sending only those could be a more complicated but also effective change.

**Comment by thorgod** [comment]
That is what I was thinking. Having channels and only updating the channels might fix that.

**Comment by apclary** [comment]
Besides what you already wrote, rather than sending the image mask as an image, the app could send information about the brush strokes in a proprietary or perhaps SVG format. I imagine the size of that would be smaller but who knows, this is sort of a special case. Perhaps something like this https://github.com/gliffy/canvas2svg
